### ISSUE TITLE
ElasticBeanstalk YML

### ISSUE THREAD

**Issue by cloudoperator** [awslabs/startup-kit-templates#3]
how far away is the Elastic Beanstalk Yaml ?

**Comment by rabowskyb** [comment]
I've just pushed up a new branch named app.  If you switch to that branch, you'll see the app template, app.cfn.yml.  

It's meant to be used with some sample workloads we've been working on.  Only one is public right now, it's at https://github.com/awslabs/startup-kit-nodejs.  It's a work in progress, but you should be able to launch it and test out everything.  If you find any issues with it, please let us know.  Thanks!

**Comment by rabowskyb** [comment]
Moved app template into master, removed app branch as it's no longer needed.

**Comment by cloudoperator** [comment]
Thanks a lot!
