### ISSUE TITLE
db.cfn.yml's DatabaseSize.AllowedPattern is a bit broken

### ISSUE THREAD

**Issue by jtmoulia** [awslabs/startup-kit-templates#5]
The pattern's purpose is to reject a number less than 5, but it rejects any number with a leading digit less than 5, e.g. 30:
```
AllowedPattern: "[5-9][0-9]*"
```

**Comment by rabowskyb** [comment]
Thanks for catching this!  Just pushed up a fix.  I'm closing out this issue, but please let us know if you run into anything else.
